name: Bucketz
author: RedCraftPE
version: 1.0.0
api: 3.0.0, 4.0.0
main: RedCraftPE\Bucketz\Main
commands:
  bucketz:
    description: The main command for GenBuckets.
    usage: /bucketz [command]
    aliases: [genbucket, bucket]
permissions:
  bucketz.give:
    description: With this command players can give themselves and others a GenBucket.
    default: op
